version: '3'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # ports:
    #   - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  api:
    image: alchemy:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8080
    depends_on:
      database:
        condition: service_completed_successfully
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_DATABASE: database
      PORT: 8080