// Code generated by ent, DO NOT EDIT.

package spacecraft

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the spacecraft type in the database.
	Label = "spacecraft"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClass holds the string denoting the class field in the database.
	FieldClass = "class"
	// FieldCrew holds the string denoting the crew field in the database.
	FieldCrew = "crew"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// EdgeArmament holds the string denoting the armament edge name in mutations.
	EdgeArmament = "armament"
	// Table holds the table name of the spacecraft in the database.
	Table = "spacecrafts"
	// ArmamentTable is the table that holds the armament relation/edge.
	ArmamentTable = "armements"
	// ArmamentInverseTable is the table name for the Armement entity.
	// It exists in this package in order to avoid circular dependency with the "armement" package.
	ArmamentInverseTable = "armements"
	// ArmamentColumn is the table column denoting the armament relation/edge.
	ArmamentColumn = "spacecraft_id"
)

// Columns holds all SQL columns for spacecraft fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldClass,
	FieldCrew,
	FieldImage,
	FieldValue,
	FieldStatus,
	FieldDeleted,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ClassValidator is a validator for the "class" field. It is called by the builders before save.
	ClassValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultDeleted holds the default value on creation for the "deleted" field.
	DefaultDeleted bool
)

// OrderOption defines the ordering options for the Spacecraft queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClass orders the results by the class field.
func ByClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClass, opts...).ToFunc()
}

// ByCrew orders the results by the crew field.
func ByCrew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrew, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeleted orders the results by the deleted field.
func ByDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleted, opts...).ToFunc()
}

// ByArmamentCount orders the results by armament count.
func ByArmamentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArmamentStep(), opts...)
	}
}

// ByArmament orders the results by armament terms.
func ByArmament(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArmamentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newArmamentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArmamentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ArmamentTable, ArmamentColumn),
	)
}
