// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArmementsColumns holds the columns for the "armements" table.
	ArmementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeString},
		{Name: "spacecraft_id", Type: field.TypeInt, Nullable: true},
	}
	// ArmementsTable holds the schema information for the "armements" table.
	ArmementsTable = &schema.Table{
		Name:       "armements",
		Columns:    ArmementsColumns,
		PrimaryKey: []*schema.Column{ArmementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "armements_spacecrafts_armament",
				Columns:    []*schema.Column{ArmementsColumns[3]},
				RefColumns: []*schema.Column{SpacecraftsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SpacecraftsColumns holds the columns for the "spacecrafts" table.
	SpacecraftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "class", Type: field.TypeString},
		{Name: "crew", Type: field.TypeUint32},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeString},
		{Name: "deleted", Type: field.TypeBool, Default: false},
	}
	// SpacecraftsTable holds the schema information for the "spacecrafts" table.
	SpacecraftsTable = &schema.Table{
		Name:       "spacecrafts",
		Columns:    SpacecraftsColumns,
		PrimaryKey: []*schema.Column{SpacecraftsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArmementsTable,
		SpacecraftsTable,
	}
)

func init() {
	ArmementsTable.ForeignKeys[0].RefTable = SpacecraftsTable
}
