// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/devshark/alchemy-fleet/ent/armement"
)

// Armement is the model entity for the Armement schema.
type Armement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity      string `json:"quantity,omitempty"`
	spacecraft_id *int
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Armement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case armement.FieldID:
			values[i] = new(sql.NullInt64)
		case armement.FieldTitle, armement.FieldQuantity:
			values[i] = new(sql.NullString)
		case armement.ForeignKeys[0]: // spacecraft_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Armement fields.
func (a *Armement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case armement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case armement.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				a.Title = value.String
			}
		case armement.FieldQuantity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				a.Quantity = value.String
			}
		case armement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field spacecraft_id", value)
			} else if value.Valid {
				a.spacecraft_id = new(int)
				*a.spacecraft_id = int(value.Int64)
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Armement.
// This includes values selected through modifiers, order, etc.
func (a *Armement) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Armement.
// Note that you need to call Armement.Unwrap() before calling this method if this Armement
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Armement) Update() *ArmementUpdateOne {
	return NewArmementClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Armement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Armement) Unwrap() *Armement {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Armement is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Armement) String() string {
	var builder strings.Builder
	builder.WriteString("Armement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("title=")
	builder.WriteString(a.Title)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(a.Quantity)
	builder.WriteByte(')')
	return builder.String()
}

// Armements is a parsable slice of Armement.
type Armements []*Armement
