// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devshark/alchemy-fleet/ent/armement"
	"github.com/devshark/alchemy-fleet/ent/predicate"
)

// ArmementUpdate is the builder for updating Armement entities.
type ArmementUpdate struct {
	config
	hooks    []Hook
	mutation *ArmementMutation
}

// Where appends a list predicates to the ArmementUpdate builder.
func (au *ArmementUpdate) Where(ps ...predicate.Armement) *ArmementUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetTitle sets the "title" field.
func (au *ArmementUpdate) SetTitle(s string) *ArmementUpdate {
	au.mutation.SetTitle(s)
	return au
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (au *ArmementUpdate) SetNillableTitle(s *string) *ArmementUpdate {
	if s != nil {
		au.SetTitle(*s)
	}
	return au
}

// SetQuantity sets the "quantity" field.
func (au *ArmementUpdate) SetQuantity(s string) *ArmementUpdate {
	au.mutation.SetQuantity(s)
	return au
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (au *ArmementUpdate) SetNillableQuantity(s *string) *ArmementUpdate {
	if s != nil {
		au.SetQuantity(*s)
	}
	return au
}

// Mutation returns the ArmementMutation object of the builder.
func (au *ArmementUpdate) Mutation() *ArmementMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArmementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArmementUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArmementUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArmementUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *ArmementUpdate) check() error {
	if v, ok := au.mutation.Title(); ok {
		if err := armement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Armement.title": %w`, err)}
		}
	}
	if v, ok := au.mutation.Quantity(); ok {
		if err := armement.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Armement.quantity": %w`, err)}
		}
	}
	return nil
}

func (au *ArmementUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(armement.Table, armement.Columns, sqlgraph.NewFieldSpec(armement.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Title(); ok {
		_spec.SetField(armement.FieldTitle, field.TypeString, value)
	}
	if value, ok := au.mutation.Quantity(); ok {
		_spec.SetField(armement.FieldQuantity, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{armement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArmementUpdateOne is the builder for updating a single Armement entity.
type ArmementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArmementMutation
}

// SetTitle sets the "title" field.
func (auo *ArmementUpdateOne) SetTitle(s string) *ArmementUpdateOne {
	auo.mutation.SetTitle(s)
	return auo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (auo *ArmementUpdateOne) SetNillableTitle(s *string) *ArmementUpdateOne {
	if s != nil {
		auo.SetTitle(*s)
	}
	return auo
}

// SetQuantity sets the "quantity" field.
func (auo *ArmementUpdateOne) SetQuantity(s string) *ArmementUpdateOne {
	auo.mutation.SetQuantity(s)
	return auo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (auo *ArmementUpdateOne) SetNillableQuantity(s *string) *ArmementUpdateOne {
	if s != nil {
		auo.SetQuantity(*s)
	}
	return auo
}

// Mutation returns the ArmementMutation object of the builder.
func (auo *ArmementUpdateOne) Mutation() *ArmementMutation {
	return auo.mutation
}

// Where appends a list predicates to the ArmementUpdate builder.
func (auo *ArmementUpdateOne) Where(ps ...predicate.Armement) *ArmementUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArmementUpdateOne) Select(field string, fields ...string) *ArmementUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Armement entity.
func (auo *ArmementUpdateOne) Save(ctx context.Context) (*Armement, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArmementUpdateOne) SaveX(ctx context.Context) *Armement {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArmementUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArmementUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *ArmementUpdateOne) check() error {
	if v, ok := auo.mutation.Title(); ok {
		if err := armement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Armement.title": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Quantity(); ok {
		if err := armement.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Armement.quantity": %w`, err)}
		}
	}
	return nil
}

func (auo *ArmementUpdateOne) sqlSave(ctx context.Context) (_node *Armement, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(armement.Table, armement.Columns, sqlgraph.NewFieldSpec(armement.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Armement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, armement.FieldID)
		for _, f := range fields {
			if !armement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != armement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Title(); ok {
		_spec.SetField(armement.FieldTitle, field.TypeString, value)
	}
	if value, ok := auo.mutation.Quantity(); ok {
		_spec.SetField(armement.FieldQuantity, field.TypeString, value)
	}
	_node = &Armement{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{armement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
