// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/devshark/alchemy-fleet/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/devshark/alchemy-fleet/ent/armement"
	"github.com/devshark/alchemy-fleet/ent/spacecraft"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Armement is the client for interacting with the Armement builders.
	Armement *ArmementClient
	// Spacecraft is the client for interacting with the Spacecraft builders.
	Spacecraft *SpacecraftClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Armement = NewArmementClient(c.config)
	c.Spacecraft = NewSpacecraftClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Armement:   NewArmementClient(cfg),
		Spacecraft: NewSpacecraftClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Armement:   NewArmementClient(cfg),
		Spacecraft: NewSpacecraftClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Armement.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Armement.Use(hooks...)
	c.Spacecraft.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Armement.Intercept(interceptors...)
	c.Spacecraft.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArmementMutation:
		return c.Armement.mutate(ctx, m)
	case *SpacecraftMutation:
		return c.Spacecraft.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArmementClient is a client for the Armement schema.
type ArmementClient struct {
	config
}

// NewArmementClient returns a client for the Armement from the given config.
func NewArmementClient(c config) *ArmementClient {
	return &ArmementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `armement.Hooks(f(g(h())))`.
func (c *ArmementClient) Use(hooks ...Hook) {
	c.hooks.Armement = append(c.hooks.Armement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `armement.Intercept(f(g(h())))`.
func (c *ArmementClient) Intercept(interceptors ...Interceptor) {
	c.inters.Armement = append(c.inters.Armement, interceptors...)
}

// Create returns a builder for creating a Armement entity.
func (c *ArmementClient) Create() *ArmementCreate {
	mutation := newArmementMutation(c.config, OpCreate)
	return &ArmementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Armement entities.
func (c *ArmementClient) CreateBulk(builders ...*ArmementCreate) *ArmementCreateBulk {
	return &ArmementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArmementClient) MapCreateBulk(slice any, setFunc func(*ArmementCreate, int)) *ArmementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArmementCreateBulk{err: fmt.Errorf("calling to ArmementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArmementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArmementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Armement.
func (c *ArmementClient) Update() *ArmementUpdate {
	mutation := newArmementMutation(c.config, OpUpdate)
	return &ArmementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArmementClient) UpdateOne(a *Armement) *ArmementUpdateOne {
	mutation := newArmementMutation(c.config, OpUpdateOne, withArmement(a))
	return &ArmementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArmementClient) UpdateOneID(id int) *ArmementUpdateOne {
	mutation := newArmementMutation(c.config, OpUpdateOne, withArmementID(id))
	return &ArmementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Armement.
func (c *ArmementClient) Delete() *ArmementDelete {
	mutation := newArmementMutation(c.config, OpDelete)
	return &ArmementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArmementClient) DeleteOne(a *Armement) *ArmementDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArmementClient) DeleteOneID(id int) *ArmementDeleteOne {
	builder := c.Delete().Where(armement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArmementDeleteOne{builder}
}

// Query returns a query builder for Armement.
func (c *ArmementClient) Query() *ArmementQuery {
	return &ArmementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArmement},
		inters: c.Interceptors(),
	}
}

// Get returns a Armement entity by its id.
func (c *ArmementClient) Get(ctx context.Context, id int) (*Armement, error) {
	return c.Query().Where(armement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArmementClient) GetX(ctx context.Context, id int) *Armement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ArmementClient) Hooks() []Hook {
	return c.hooks.Armement
}

// Interceptors returns the client interceptors.
func (c *ArmementClient) Interceptors() []Interceptor {
	return c.inters.Armement
}

func (c *ArmementClient) mutate(ctx context.Context, m *ArmementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArmementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArmementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArmementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArmementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Armement mutation op: %q", m.Op())
	}
}

// SpacecraftClient is a client for the Spacecraft schema.
type SpacecraftClient struct {
	config
}

// NewSpacecraftClient returns a client for the Spacecraft from the given config.
func NewSpacecraftClient(c config) *SpacecraftClient {
	return &SpacecraftClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `spacecraft.Hooks(f(g(h())))`.
func (c *SpacecraftClient) Use(hooks ...Hook) {
	c.hooks.Spacecraft = append(c.hooks.Spacecraft, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `spacecraft.Intercept(f(g(h())))`.
func (c *SpacecraftClient) Intercept(interceptors ...Interceptor) {
	c.inters.Spacecraft = append(c.inters.Spacecraft, interceptors...)
}

// Create returns a builder for creating a Spacecraft entity.
func (c *SpacecraftClient) Create() *SpacecraftCreate {
	mutation := newSpacecraftMutation(c.config, OpCreate)
	return &SpacecraftCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Spacecraft entities.
func (c *SpacecraftClient) CreateBulk(builders ...*SpacecraftCreate) *SpacecraftCreateBulk {
	return &SpacecraftCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SpacecraftClient) MapCreateBulk(slice any, setFunc func(*SpacecraftCreate, int)) *SpacecraftCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SpacecraftCreateBulk{err: fmt.Errorf("calling to SpacecraftClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SpacecraftCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SpacecraftCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Spacecraft.
func (c *SpacecraftClient) Update() *SpacecraftUpdate {
	mutation := newSpacecraftMutation(c.config, OpUpdate)
	return &SpacecraftUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SpacecraftClient) UpdateOne(s *Spacecraft) *SpacecraftUpdateOne {
	mutation := newSpacecraftMutation(c.config, OpUpdateOne, withSpacecraft(s))
	return &SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SpacecraftClient) UpdateOneID(id int) *SpacecraftUpdateOne {
	mutation := newSpacecraftMutation(c.config, OpUpdateOne, withSpacecraftID(id))
	return &SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Spacecraft.
func (c *SpacecraftClient) Delete() *SpacecraftDelete {
	mutation := newSpacecraftMutation(c.config, OpDelete)
	return &SpacecraftDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SpacecraftClient) DeleteOne(s *Spacecraft) *SpacecraftDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SpacecraftClient) DeleteOneID(id int) *SpacecraftDeleteOne {
	builder := c.Delete().Where(spacecraft.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SpacecraftDeleteOne{builder}
}

// Query returns a query builder for Spacecraft.
func (c *SpacecraftClient) Query() *SpacecraftQuery {
	return &SpacecraftQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSpacecraft},
		inters: c.Interceptors(),
	}
}

// Get returns a Spacecraft entity by its id.
func (c *SpacecraftClient) Get(ctx context.Context, id int) (*Spacecraft, error) {
	return c.Query().Where(spacecraft.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SpacecraftClient) GetX(ctx context.Context, id int) *Spacecraft {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArmament queries the armament edge of a Spacecraft.
func (c *SpacecraftClient) QueryArmament(s *Spacecraft) *ArmementQuery {
	query := (&ArmementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(spacecraft.Table, spacecraft.FieldID, id),
			sqlgraph.To(armement.Table, armement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, spacecraft.ArmamentTable, spacecraft.ArmamentColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SpacecraftClient) Hooks() []Hook {
	return c.hooks.Spacecraft
}

// Interceptors returns the client interceptors.
func (c *SpacecraftClient) Interceptors() []Interceptor {
	return c.inters.Spacecraft
}

func (c *SpacecraftClient) mutate(ctx context.Context, m *SpacecraftMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SpacecraftCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SpacecraftUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SpacecraftDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Spacecraft mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Armement, Spacecraft []ent.Hook
	}
	inters struct {
		Armement, Spacecraft []ent.Interceptor
	}
)
