// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/devshark/alchemy-fleet/ent/armement"
	"github.com/devshark/alchemy-fleet/ent/predicate"
	"github.com/devshark/alchemy-fleet/ent/spacecraft"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeArmement   = "Armement"
	TypeSpacecraft = "Spacecraft"
)

// ArmementMutation represents an operation that mutates the Armement nodes in the graph.
type ArmementMutation struct {
	config
	op            Op
	typ           string
	id            *int
	title         *string
	quantity      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Armement, error)
	predicates    []predicate.Armement
}

var _ ent.Mutation = (*ArmementMutation)(nil)

// armementOption allows management of the mutation configuration using functional options.
type armementOption func(*ArmementMutation)

// newArmementMutation creates new mutation for the Armement entity.
func newArmementMutation(c config, op Op, opts ...armementOption) *ArmementMutation {
	m := &ArmementMutation{
		config:        c,
		op:            op,
		typ:           TypeArmement,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withArmementID sets the ID field of the mutation.
func withArmementID(id int) armementOption {
	return func(m *ArmementMutation) {
		var (
			err   error
			once  sync.Once
			value *Armement
		)
		m.oldValue = func(ctx context.Context) (*Armement, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Armement.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withArmement sets the old Armement of the mutation.
func withArmement(node *Armement) armementOption {
	return func(m *ArmementMutation) {
		m.oldValue = func(context.Context) (*Armement, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ArmementMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ArmementMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ArmementMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ArmementMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Armement.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *ArmementMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ArmementMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Armement entity.
// If the Armement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArmementMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ArmementMutation) ResetTitle() {
	m.title = nil
}

// SetQuantity sets the "quantity" field.
func (m *ArmementMutation) SetQuantity(s string) {
	m.quantity = &s
}

// Quantity returns the value of the "quantity" field in the mutation.
func (m *ArmementMutation) Quantity() (r string, exists bool) {
	v := m.quantity
	if v == nil {
		return
	}
	return *v, true
}

// OldQuantity returns the old "quantity" field's value of the Armement entity.
// If the Armement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArmementMutation) OldQuantity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuantity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuantity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuantity: %w", err)
	}
	return oldValue.Quantity, nil
}

// ResetQuantity resets all changes to the "quantity" field.
func (m *ArmementMutation) ResetQuantity() {
	m.quantity = nil
}

// Where appends a list predicates to the ArmementMutation builder.
func (m *ArmementMutation) Where(ps ...predicate.Armement) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ArmementMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ArmementMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Armement, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ArmementMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ArmementMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Armement).
func (m *ArmementMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ArmementMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.title != nil {
		fields = append(fields, armement.FieldTitle)
	}
	if m.quantity != nil {
		fields = append(fields, armement.FieldQuantity)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ArmementMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case armement.FieldTitle:
		return m.Title()
	case armement.FieldQuantity:
		return m.Quantity()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ArmementMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case armement.FieldTitle:
		return m.OldTitle(ctx)
	case armement.FieldQuantity:
		return m.OldQuantity(ctx)
	}
	return nil, fmt.Errorf("unknown Armement field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArmementMutation) SetField(name string, value ent.Value) error {
	switch name {
	case armement.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case armement.FieldQuantity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuantity(v)
		return nil
	}
	return fmt.Errorf("unknown Armement field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ArmementMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ArmementMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArmementMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Armement numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ArmementMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ArmementMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ArmementMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Armement nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ArmementMutation) ResetField(name string) error {
	switch name {
	case armement.FieldTitle:
		m.ResetTitle()
		return nil
	case armement.FieldQuantity:
		m.ResetQuantity()
		return nil
	}
	return fmt.Errorf("unknown Armement field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ArmementMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ArmementMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ArmementMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ArmementMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ArmementMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ArmementMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ArmementMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Armement unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ArmementMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Armement edge %s", name)
}

// SpacecraftMutation represents an operation that mutates the Spacecraft nodes in the graph.
type SpacecraftMutation struct {
	config
	op              Op
	typ             string
	id              *int
	name            *string
	class           *string
	crew            *uint32
	addcrew         *int32
	image           *string
	value           *float64
	addvalue        *float64
	status          *string
	deleted         *bool
	clearedFields   map[string]struct{}
	armament        map[int]struct{}
	removedarmament map[int]struct{}
	clearedarmament bool
	done            bool
	oldValue        func(context.Context) (*Spacecraft, error)
	predicates      []predicate.Spacecraft
}

var _ ent.Mutation = (*SpacecraftMutation)(nil)

// spacecraftOption allows management of the mutation configuration using functional options.
type spacecraftOption func(*SpacecraftMutation)

// newSpacecraftMutation creates new mutation for the Spacecraft entity.
func newSpacecraftMutation(c config, op Op, opts ...spacecraftOption) *SpacecraftMutation {
	m := &SpacecraftMutation{
		config:        c,
		op:            op,
		typ:           TypeSpacecraft,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSpacecraftID sets the ID field of the mutation.
func withSpacecraftID(id int) spacecraftOption {
	return func(m *SpacecraftMutation) {
		var (
			err   error
			once  sync.Once
			value *Spacecraft
		)
		m.oldValue = func(ctx context.Context) (*Spacecraft, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Spacecraft.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSpacecraft sets the old Spacecraft of the mutation.
func withSpacecraft(node *Spacecraft) spacecraftOption {
	return func(m *SpacecraftMutation) {
		m.oldValue = func(context.Context) (*Spacecraft, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SpacecraftMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SpacecraftMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SpacecraftMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SpacecraftMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Spacecraft.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SpacecraftMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SpacecraftMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SpacecraftMutation) ResetName() {
	m.name = nil
}

// SetClass sets the "class" field.
func (m *SpacecraftMutation) SetClass(s string) {
	m.class = &s
}

// Class returns the value of the "class" field in the mutation.
func (m *SpacecraftMutation) Class() (r string, exists bool) {
	v := m.class
	if v == nil {
		return
	}
	return *v, true
}

// OldClass returns the old "class" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldClass(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClass is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClass requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClass: %w", err)
	}
	return oldValue.Class, nil
}

// ResetClass resets all changes to the "class" field.
func (m *SpacecraftMutation) ResetClass() {
	m.class = nil
}

// SetCrew sets the "crew" field.
func (m *SpacecraftMutation) SetCrew(u uint32) {
	m.crew = &u
	m.addcrew = nil
}

// Crew returns the value of the "crew" field in the mutation.
func (m *SpacecraftMutation) Crew() (r uint32, exists bool) {
	v := m.crew
	if v == nil {
		return
	}
	return *v, true
}

// OldCrew returns the old "crew" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldCrew(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCrew is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCrew requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCrew: %w", err)
	}
	return oldValue.Crew, nil
}

// AddCrew adds u to the "crew" field.
func (m *SpacecraftMutation) AddCrew(u int32) {
	if m.addcrew != nil {
		*m.addcrew += u
	} else {
		m.addcrew = &u
	}
}

// AddedCrew returns the value that was added to the "crew" field in this mutation.
func (m *SpacecraftMutation) AddedCrew() (r int32, exists bool) {
	v := m.addcrew
	if v == nil {
		return
	}
	return *v, true
}

// ResetCrew resets all changes to the "crew" field.
func (m *SpacecraftMutation) ResetCrew() {
	m.crew = nil
	m.addcrew = nil
}

// SetImage sets the "image" field.
func (m *SpacecraftMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *SpacecraftMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ClearImage clears the value of the "image" field.
func (m *SpacecraftMutation) ClearImage() {
	m.image = nil
	m.clearedFields[spacecraft.FieldImage] = struct{}{}
}

// ImageCleared returns if the "image" field was cleared in this mutation.
func (m *SpacecraftMutation) ImageCleared() bool {
	_, ok := m.clearedFields[spacecraft.FieldImage]
	return ok
}

// ResetImage resets all changes to the "image" field.
func (m *SpacecraftMutation) ResetImage() {
	m.image = nil
	delete(m.clearedFields, spacecraft.FieldImage)
}

// SetValue sets the "value" field.
func (m *SpacecraftMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *SpacecraftMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *SpacecraftMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *SpacecraftMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *SpacecraftMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// SetStatus sets the "status" field.
func (m *SpacecraftMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SpacecraftMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SpacecraftMutation) ResetStatus() {
	m.status = nil
}

// SetDeleted sets the "deleted" field.
func (m *SpacecraftMutation) SetDeleted(b bool) {
	m.deleted = &b
}

// Deleted returns the value of the "deleted" field in the mutation.
func (m *SpacecraftMutation) Deleted() (r bool, exists bool) {
	v := m.deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleted returns the old "deleted" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldDeleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleted: %w", err)
	}
	return oldValue.Deleted, nil
}

// ResetDeleted resets all changes to the "deleted" field.
func (m *SpacecraftMutation) ResetDeleted() {
	m.deleted = nil
}

// AddArmamentIDs adds the "armament" edge to the Armement entity by ids.
func (m *SpacecraftMutation) AddArmamentIDs(ids ...int) {
	if m.armament == nil {
		m.armament = make(map[int]struct{})
	}
	for i := range ids {
		m.armament[ids[i]] = struct{}{}
	}
}

// ClearArmament clears the "armament" edge to the Armement entity.
func (m *SpacecraftMutation) ClearArmament() {
	m.clearedarmament = true
}

// ArmamentCleared reports if the "armament" edge to the Armement entity was cleared.
func (m *SpacecraftMutation) ArmamentCleared() bool {
	return m.clearedarmament
}

// RemoveArmamentIDs removes the "armament" edge to the Armement entity by IDs.
func (m *SpacecraftMutation) RemoveArmamentIDs(ids ...int) {
	if m.removedarmament == nil {
		m.removedarmament = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.armament, ids[i])
		m.removedarmament[ids[i]] = struct{}{}
	}
}

// RemovedArmament returns the removed IDs of the "armament" edge to the Armement entity.
func (m *SpacecraftMutation) RemovedArmamentIDs() (ids []int) {
	for id := range m.removedarmament {
		ids = append(ids, id)
	}
	return
}

// ArmamentIDs returns the "armament" edge IDs in the mutation.
func (m *SpacecraftMutation) ArmamentIDs() (ids []int) {
	for id := range m.armament {
		ids = append(ids, id)
	}
	return
}

// ResetArmament resets all changes to the "armament" edge.
func (m *SpacecraftMutation) ResetArmament() {
	m.armament = nil
	m.clearedarmament = false
	m.removedarmament = nil
}

// Where appends a list predicates to the SpacecraftMutation builder.
func (m *SpacecraftMutation) Where(ps ...predicate.Spacecraft) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SpacecraftMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SpacecraftMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Spacecraft, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SpacecraftMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SpacecraftMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Spacecraft).
func (m *SpacecraftMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SpacecraftMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.name != nil {
		fields = append(fields, spacecraft.FieldName)
	}
	if m.class != nil {
		fields = append(fields, spacecraft.FieldClass)
	}
	if m.crew != nil {
		fields = append(fields, spacecraft.FieldCrew)
	}
	if m.image != nil {
		fields = append(fields, spacecraft.FieldImage)
	}
	if m.value != nil {
		fields = append(fields, spacecraft.FieldValue)
	}
	if m.status != nil {
		fields = append(fields, spacecraft.FieldStatus)
	}
	if m.deleted != nil {
		fields = append(fields, spacecraft.FieldDeleted)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SpacecraftMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case spacecraft.FieldName:
		return m.Name()
	case spacecraft.FieldClass:
		return m.Class()
	case spacecraft.FieldCrew:
		return m.Crew()
	case spacecraft.FieldImage:
		return m.Image()
	case spacecraft.FieldValue:
		return m.Value()
	case spacecraft.FieldStatus:
		return m.Status()
	case spacecraft.FieldDeleted:
		return m.Deleted()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SpacecraftMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case spacecraft.FieldName:
		return m.OldName(ctx)
	case spacecraft.FieldClass:
		return m.OldClass(ctx)
	case spacecraft.FieldCrew:
		return m.OldCrew(ctx)
	case spacecraft.FieldImage:
		return m.OldImage(ctx)
	case spacecraft.FieldValue:
		return m.OldValue(ctx)
	case spacecraft.FieldStatus:
		return m.OldStatus(ctx)
	case spacecraft.FieldDeleted:
		return m.OldDeleted(ctx)
	}
	return nil, fmt.Errorf("unknown Spacecraft field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SpacecraftMutation) SetField(name string, value ent.Value) error {
	switch name {
	case spacecraft.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case spacecraft.FieldClass:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClass(v)
		return nil
	case spacecraft.FieldCrew:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCrew(v)
		return nil
	case spacecraft.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case spacecraft.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case spacecraft.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case spacecraft.FieldDeleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown Spacecraft field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SpacecraftMutation) AddedFields() []string {
	var fields []string
	if m.addcrew != nil {
		fields = append(fields, spacecraft.FieldCrew)
	}
	if m.addvalue != nil {
		fields = append(fields, spacecraft.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SpacecraftMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case spacecraft.FieldCrew:
		return m.AddedCrew()
	case spacecraft.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SpacecraftMutation) AddField(name string, value ent.Value) error {
	switch name {
	case spacecraft.FieldCrew:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCrew(v)
		return nil
	case spacecraft.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown Spacecraft numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SpacecraftMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(spacecraft.FieldImage) {
		fields = append(fields, spacecraft.FieldImage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SpacecraftMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SpacecraftMutation) ClearField(name string) error {
	switch name {
	case spacecraft.FieldImage:
		m.ClearImage()
		return nil
	}
	return fmt.Errorf("unknown Spacecraft nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SpacecraftMutation) ResetField(name string) error {
	switch name {
	case spacecraft.FieldName:
		m.ResetName()
		return nil
	case spacecraft.FieldClass:
		m.ResetClass()
		return nil
	case spacecraft.FieldCrew:
		m.ResetCrew()
		return nil
	case spacecraft.FieldImage:
		m.ResetImage()
		return nil
	case spacecraft.FieldValue:
		m.ResetValue()
		return nil
	case spacecraft.FieldStatus:
		m.ResetStatus()
		return nil
	case spacecraft.FieldDeleted:
		m.ResetDeleted()
		return nil
	}
	return fmt.Errorf("unknown Spacecraft field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SpacecraftMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.armament != nil {
		edges = append(edges, spacecraft.EdgeArmament)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SpacecraftMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case spacecraft.EdgeArmament:
		ids := make([]ent.Value, 0, len(m.armament))
		for id := range m.armament {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SpacecraftMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedarmament != nil {
		edges = append(edges, spacecraft.EdgeArmament)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SpacecraftMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case spacecraft.EdgeArmament:
		ids := make([]ent.Value, 0, len(m.removedarmament))
		for id := range m.removedarmament {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SpacecraftMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedarmament {
		edges = append(edges, spacecraft.EdgeArmament)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SpacecraftMutation) EdgeCleared(name string) bool {
	switch name {
	case spacecraft.EdgeArmament:
		return m.clearedarmament
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SpacecraftMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Spacecraft unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SpacecraftMutation) ResetEdge(name string) error {
	switch name {
	case spacecraft.EdgeArmament:
		m.ResetArmament()
		return nil
	}
	return fmt.Errorf("unknown Spacecraft edge %s", name)
}
