// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/devshark/alchemy-fleet/ent/armement"
	"github.com/devshark/alchemy-fleet/ent/schema"
	"github.com/devshark/alchemy-fleet/ent/spacecraft"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	armementFields := schema.Armement{}.Fields()
	_ = armementFields
	// armementDescTitle is the schema descriptor for title field.
	armementDescTitle := armementFields[0].Descriptor()
	// armement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	armement.TitleValidator = armementDescTitle.Validators[0].(func(string) error)
	// armementDescQuantity is the schema descriptor for quantity field.
	armementDescQuantity := armementFields[1].Descriptor()
	// armement.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	armement.QuantityValidator = armementDescQuantity.Validators[0].(func(string) error)
	spacecraftFields := schema.Spacecraft{}.Fields()
	_ = spacecraftFields
	// spacecraftDescName is the schema descriptor for name field.
	spacecraftDescName := spacecraftFields[0].Descriptor()
	// spacecraft.NameValidator is a validator for the "name" field. It is called by the builders before save.
	spacecraft.NameValidator = spacecraftDescName.Validators[0].(func(string) error)
	// spacecraftDescClass is the schema descriptor for class field.
	spacecraftDescClass := spacecraftFields[1].Descriptor()
	// spacecraft.ClassValidator is a validator for the "class" field. It is called by the builders before save.
	spacecraft.ClassValidator = spacecraftDescClass.Validators[0].(func(string) error)
	// spacecraftDescStatus is the schema descriptor for status field.
	spacecraftDescStatus := spacecraftFields[5].Descriptor()
	// spacecraft.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	spacecraft.StatusValidator = spacecraftDescStatus.Validators[0].(func(string) error)
	// spacecraftDescDeleted is the schema descriptor for deleted field.
	spacecraftDescDeleted := spacecraftFields[6].Descriptor()
	// spacecraft.DefaultDeleted holds the default value on creation for the deleted field.
	spacecraft.DefaultDeleted = spacecraftDescDeleted.Default.(bool)
}
