// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Armement is the predicate function for armement builders.
type Armement func(*sql.Selector)

// Spacecraft is the predicate function for spacecraft builders.
type Spacecraft func(*sql.Selector)
